// ── State ─────────────────────────────────────────────────────────────────────
const state = {
  discs: [],
  currentDiscId: null,
  currentTrackIndex: -1,
  seeking: false,
  sidebarCollapsed: false,
  browseDir: '',
  favorites: new Map(),
  queue: [],
  bookmarks: {},
  collapsedDiscs: new Set(),
};

// ── Persistence ───────────────────────────────────────────────────────────────
const STORAGE = {
  getDir:      ()    => localStorage.getItem('tlp_dir') || '',
  setDir:      (v)   => localStorage.setItem('tlp_dir', v),
  getTheme:    ()    => localStorage.getItem('tlp_theme') || 'dark',
  setTheme:    (v)   => localStorage.setItem('tlp_theme', v),
  getSidebarW: ()    => localStorage.getItem('tlp_sidebar_w') || '340',
  setSidebarW: (v)   => localStorage.setItem('tlp_sidebar_w', String(v)),
  getBrowserH:    ()    => localStorage.getItem('tlp_browser_h') || '40',
  getWaveformOn:  ()    => localStorage.getItem('tlp_waveform') !== 'off',
  setWaveformOn:  (v)   => localStorage.setItem('tlp_waveform', v ? 'on' : 'off'),
  getMainTopH:    ()    => parseInt(localStorage.getItem('tlp_main_top_h'), 10) || 0,
  setMainTopH:    (v)   => localStorage.setItem('tlp_main_top_h', String(v)),
  setBrowserH: (v)   => localStorage.setItem('tlp_browser_h', String(v)),
  getFavs:     ()    => JSON.parse(localStorage.getItem('tlp_favorites') || '[]'),
  setFavs:     (arr) => localStorage.setItem('tlp_favorites', JSON.stringify(arr)),
  getPlayState: ()   => JSON.parse(localStorage.getItem('tlp_playstate') || 'null'),
  setPlayState: (v)  => localStorage.setItem('tlp_playstate', JSON.stringify(v)),
  getScanDir:   ()    => localStorage.getItem('tlp_scan_dir') || '',
  setScanDir:   (v)   => localStorage.setItem('tlp_scan_dir', v),
  getFilter:    ()    => localStorage.getItem('tlp_filter') || '',
  setFilter:    (v)   => localStorage.setItem('tlp_filter', v),
  getVolume:    ()    => parseFloat(localStorage.getItem('tlp_volume') ?? '1'),
  setVolume:    (v)   => localStorage.setItem('tlp_volume', String(v)),
  getShuffle:   ()    => localStorage.getItem('tlp_shuffle') === 'on',
  setShuffle:   (v)   => localStorage.setItem('tlp_shuffle', v ? 'on' : 'off'),
  getRepeat:    ()    => localStorage.getItem('tlp_repeat') || 'off',
  setRepeat:    (v)   => localStorage.setItem('tlp_repeat', v),
  getSpectrumRes: ()  => parseInt(localStorage.getItem('tlp_spectrum_res') || '100', 10),
  setSpectrumRes: (v) => localStorage.setItem('tlp_spectrum_res', String(v)),
  getTrackLabels: ()  => localStorage.getItem('tlp_track_labels') !== 'off',
  setTrackLabels: (v) => localStorage.setItem('tlp_track_labels', v ? 'on' : 'off'),
  getStreamSession: ()  => JSON.parse(localStorage.getItem('tlp_stream_session') || 'null'),
  setStreamSession: (v) => localStorage.setItem('tlp_stream_session', JSON.stringify(v)),
  clearStreamSession: () => localStorage.removeItem('tlp_stream_session'),
  getDiscProgress: ()  => JSON.parse(localStorage.getItem('tlp_disc_progress') || '{}'),
  setDiscProgress: (v) => localStorage.setItem('tlp_disc_progress', JSON.stringify(v)),
  getEqLow:    ()  => parseFloat(localStorage.getItem('tlp_eq_low') || '0'),
  setEqLow:    (v) => localStorage.setItem('tlp_eq_low', String(v)),
  getEqMid:    ()  => parseFloat(localStorage.getItem('tlp_eq_mid') || '0'),
  setEqMid:    (v) => localStorage.setItem('tlp_eq_mid', String(v)),
  getEqHigh:   ()  => parseFloat(localStorage.getItem('tlp_eq_high') || '0'),
  setEqHigh:   (v) => localStorage.setItem('tlp_eq_high', String(v)),
  getBookmarks: ()  => JSON.parse(localStorage.getItem('tlp_bookmarks') || '{}'),
  setBookmarks: (v) => localStorage.setItem('tlp_bookmarks', JSON.stringify(v)),
  getQueue:     ()  => JSON.parse(localStorage.getItem('tlp_play_queue') || '[]'),
  setQueue:     (v) => localStorage.setItem('tlp_play_queue', JSON.stringify(v)),
  getSpotifyTargetPlaylist: () => localStorage.getItem('tlp_spotify_target_playlist') || '',
  setSpotifyTargetPlaylist: (v) => localStorage.setItem('tlp_spotify_target_playlist', v),
  getBpmCache:  ()  => JSON.parse(localStorage.getItem('tlp_bpm_cache') || '{}'),
  setBpmCache:  (v) => localStorage.setItem('tlp_bpm_cache', JSON.stringify(v)),
};

export { state, STORAGE };
